### ISSUE TITLE
Group classes and properties together with their function

### ISSUE THREAD

**Issue by mrpatrickwest** [tetherless-world/dco-ontology#12]
For example, project update classes and properties could be grouped together, making it easier to review and read through the ontology.

Question: @zednis what tool have you been using to create these .ttl files?
Question: is it possible to group classes and properties together?

**Comment by zednis** [comment]
I believe the file structure, formatting, and resource order is essentially unmodified from what was generated via the VIVO ontology export functionality.

**Comment by mrpatrickwest** [comment]
re-organized and prettied up. Added ontology annotations.
