### ISSUE TITLE
Create descriptions for all of the classes and properties

### ISSUE THREAD

**Issue by mrpatrickwest** [tetherless-world/dco-ontology#15]
And don't use the class or property name alone in the description. What is a dco:VesselIMO, for example.

**Comment by zednis** [comment]
I am guessing it is the International Maritime Organization (IMO) number for the vessel.

https://en.wikipedia.org/wiki/IMO_number

:+1: with Patrick's suggestion to create a description.

**Comment by mrpatrickwest** [comment]
Labels and comments have been added for all of the classes and properties.
