### ISSUE TITLE
dco:projectUpdates should be removed as it has been replaced with the new project update ontology

### ISSUE THREAD

**Issue by mrpatrickwest** [tetherless-world/dco-ontology#36]
This is what was used in the summer of 2014. Since then we've developed the new ontology for project updates. This is a deprecated property and should be removed. There are currently no individuals using this property so could be safely removed.

```
dco:projectUpdates
      a       owl:DatatypeProperty ;
      rdfs:domain vivo:Project ;
      rdfs:label "project updates"@en-US ;
      rdfs:range xsd:string .
```

**Comment by zednis** [comment]
:+1:

**Comment by mrpatrickwest** [comment]
removed
